name: ROS2 CI

on: [push, pull_request]

jobs:
  ros_gz_ci:
    name: ros_gz CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: "ubuntu:24.04"
            gz-version: "harmonic"
<<<<<<< HEAD
            ros-distro: "jazzy"
=======
            ros-distro: "rolling"
>>>>>>> 63b651a (Garden EOL (#662))
    container:
      image: ${{ matrix.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: .github/workflows/build-and-test.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker-image }}
          GZ_VERSION: ${{ matrix.gz-version  }}
          ROS_DISTRO: ${{ matrix.ros-distro }}
