on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
name: Ticket opened
jobs:
  assign:
    name: Add ticket to inbox
    runs-on: ubuntu-latest
    steps:
      - name: Add ticket to inbox
<<<<<<< HEAD
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Core development
          COLUMN: Inbox
          GITHUB_TOKEN: ${{ secrets.TRIAGE_TOKEN }}
          CHECK_ORG_PROJECT: true
=======
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/gazebosim/projects/7
          github-token: ${{ secrets.TRIAGE_TOKEN }}
>>>>>>> 63b651a (Garden EOL (#662))

